Repository MollyWhopStudios/VibeMaster, pull requests merged in 2019-04, with the labels that each got.

#22 fixed particles
  Assets/Scenes/Main Menu.unity
Labels: fix

#23 stats panel text display
  Assets/Scenes/Game.unity
  Assets/Scripts/Game.cs
  Assets/Scripts/StatsFunctions.cs
  Assets/Scripts/StatsFunctions.cs.meta
Labels: enhancement

#24 game-particles
  Assets/Scenes/Game.unity
Labels: fix

#25 critters
  Assets/Animations/Critter.controller
  Assets/Animations/Critter.controller.meta
  Assets/Animations/critterJiggle.anim
  Assets/Animations/critterJiggle.anim.meta
  Assets/Scenes/Game.unity
  Assets/Scenes/Main Menu.unity
  Assets/Scripts/MainMenuFunctions.cs
  Assets/Scripts/MainMenuFunctions.cs.meta
Labels: enhancement

#26 critter 1
  Assets/Animations/critterJiggle.anim
  Assets/Animations/lozanoPeek.anim
  Assets/Animations/lozanoPeek.anim.meta
  Assets/Scenes/Main Menu.unity
  Assets/Scripts/MainMenuFunctions.cs
Labels: enhancement

#27 critters+
  Assets/Animations/MainMenuAnim.meta
  Assets/Animations/MainMenuAnim/CritterFour.controller
  Assets/Animations/MainMenuAnim/CritterFour.controller.meta
  Assets/Animations/MainMenuAnim/CritterThree.controller
  Assets/Animations/MainMenuAnim/CritterThree.controller.meta
  Assets/Animations/MainMenuAnim/JossEnter.anim
  Assets/Animations/MainMenuAnim/JossEnter.anim.meta
  Assets/Animations/MainMenuAnim/jossLeave.anim
  Assets/Animations/MainMenuAnim/jossLeave.anim.meta
  Assets/Animations/MainMenuAnim/jossSlide.anim
  Assets/Animations/MainMenuAnim/jossSlide.anim.meta
  Assets/Animations/MainMenuAnim/jossSlide1.anim
  Assets/Animations/MainMenuAnim/jossSlide1.anim.meta
  Assets/Animations/MainMenuAnim/jossSlide2.anim
  Assets/Animations/MainMenuAnim/jossSlide2.anim.meta
  Assets/Animations/MainMenuAnim/lozanoEnter.anim
  Assets/Animations/MainMenuAnim/lozanoEnter.anim.meta
  Assets/Animations/MainMenuAnim/lozanoLeave.anim
  Assets/Animations/MainMenuAnim/lozanoLeave.anim.meta
  Assets/Animations/MainMenuAnim/lozanoSlide.anim
  Assets/Animations/MainMenuAnim/lozanoSlide.anim.meta
  Assets/Animations/MainMenuAnim/lozanoSlide1.anim
  Assets/Animations/MainMenuAnim/lozanoSlide1.anim.meta
  Assets/Animations/MainMenuAnim/lozanoSlide2.anim
  Assets/Animations/MainMenuAnim/lozanoSlide2.anim.meta
  Assets/Animations/critterJiggleBack.anim
  Assets/Animations/critterJiggleBack.anim.meta
  Assets/Scenes/Game.unity
  Assets/Scenes/Main Menu.unity
  Assets/Scripts/Game.cs
  Assets/Scripts/MainMenuFunctions.cs
  Assets/Sprites/glowstick-tickets.png
  Assets/Sprites/glowstick-tickets.png.meta
  Assets/Sprites/jossboss.png
  Assets/Sprites/jossboss.png.meta
  Assets/Sprites/lozanoMonka.png
  Assets/Sprites/lozanoMonka.png.meta
Labels: enhancement

#30 Music function revamp
  Assets/Animations/musicPanelSlide.anim
  Assets/Animations/musicPanelSlideOff.anim
  Assets/Music.meta
  Assets/Scenes/Game.unity
  Assets/Scenes/Main Menu.unity
  Assets/Scripts/MusicFunctions.cs
  Assets/Scripts/MusicPlayer.cs
  Assets/Scripts/SceneLoader.cs
  Assets/Sprites/eighthNote.png
  Assets/Sprites/eighthNote.png.meta
Labels: bug, enhancement, fix

#32 Update Main Menu.unity
  Assets/Scenes/Main Menu.unity
Labels: UI Change

#33 sound patch
  Assets/Animations/volumeChangeAnimation.anim
  Assets/Animations/volumeChangeAnimation.anim.meta
  Assets/Resources/hotel_pools_spring.mp3
  Assets/Resources/hotel_pools_spring.mp3.meta
  Assets/Scenes/Game.unity
  Assets/Scenes/Main Menu.unity
  Assets/Scripts/Game.cs
  Assets/Scripts/MusicFunctions.cs
  Assets/Scripts/MusicPlayer.cs
  Assets/Scripts/SceneLoader.cs
Labels: enhancement

#35 Mini game scenes
  Assets/Scenes/Game.unity
  Assets/Scenes/Level 1.unity
  Assets/Scenes/Level 1.unity.meta
  Assets/Scenes/Level 2.unity
  Assets/Scenes/Level 2.unity.meta
  Assets/Scenes/Level 3.unity
  Assets/Scenes/Level 3.unity.meta
  Assets/Scenes/Mini Games.unity
  Assets/Scenes/Options.unity
  Assets/Scripts/SceneLoader.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#36 Mini game
  Assets/Mini Games/Bullet Hell/Paths/Path (0).prefab
  Assets/Mini Games/Bullet Hell/Scripts/BH_Enemy.cs
  Assets/Mini Games/Bullet Hell/Scripts/BH_Player.cs
  Assets/Mini Games/Bullet Hell/Waves/Level 1.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 1/wave 1.asset
  Assets/Mini Games/Bullet Hell/Waves/Level 1/wave 1.asset.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 1/wave 2.asset
  Assets/Mini Games/Bullet Hell/Waves/Level 1/wave 2.asset.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 1/wave 3.asset
  Assets/Mini Games/Bullet Hell/Waves/Level 1/wave 3.asset.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 1/wave 4.asset
  Assets/Mini Games/Bullet Hell/Waves/Level 1/wave 4.asset.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 2.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 2/wave 1.asset
  Assets/Mini Games/Bullet Hell/Waves/Level 2/wave 1.asset.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 2/wave 2.asset
  Assets/Mini Games/Bullet Hell/Waves/Level 2/wave 2.asset.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 2/wave 3.asset
  Assets/Mini Games/Bullet Hell/Waves/Level 2/wave 3.asset.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 2/wave 4.asset
  Assets/Mini Games/Bullet Hell/Waves/Level 2/wave 4.asset.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 3.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 3/wave 1.asset
  Assets/Mini Games/Bullet Hell/Waves/Level 3/wave 1.asset.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 3/wave 2.asset
  Assets/Mini Games/Bullet Hell/Waves/Level 3/wave 2.asset.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 3/wave 3.asset
  Assets/Mini Games/Bullet Hell/Waves/Level 3/wave 3.asset.meta
  Assets/Mini Games/Bullet Hell/Waves/Level 3/wave 4.asset
  Assets/Mini Games/Bullet Hell/Waves/Level 3/wave 4.asset.meta
  Assets/Scenes/Game.unity
  Assets/Scenes/Level 1.unity
  Assets/Scenes/Level 2.unity
  Assets/Scenes/Level 3.unity
Labels: enhancement

#37 mini game panel
  Assets/Animations/MiniGamePanel.controller
  Assets/Animations/MiniGamePanel.controller.meta
  Assets/Animations/miniGamePanelSlide.anim
  Assets/Animations/miniGamePanelSlide.anim.meta
  Assets/Animations/miniGamePanelSlideOff.anim
  Assets/Animations/miniGamePanelSlideOff.anim.meta
  Assets/Scripts/SceneLoader.cs
Labels: enhancement

#38 mini game panel slide
  Assets/Animations/miniGamePanelSlide.anim
  Assets/Scripts/SceneLoader.cs
Labels: enhancement
